server:
  port: 8005

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: szcwm
    password: szcwm
  cloud:
    consul:
      host: 192.168.248.130
      port: 8500
      discovery:
        service-name: ${spring.application.name}

mybatis:
  mapper-locations: classpath:com.silent.springcloud.dao/*.xml
  type-aliases-package: com.silent.springcloud.entity
