server:
  port: 8003

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
    username: szcwm
    password: szcwm
  cloud:
    zookeeper:
      connect-string: 192.168.248.130:2181,192.168.248.130:2182,192.168.248.130:2183

mybatis:
  mapper-locations: classpath:com.silent.springcloud.dao/*.xml
  type-aliases-package: com.silent.springcloud.entity
