server:
  port: 80
spring:
  application:
    name: cloud-order-service
  main:
    allow-bean-definition-overriding: true

#开启Feign的hystrix，这样配置文件中的hystrix的配置才会生效，否则依然是默认的规则
feign:
  hystrix:
    enabled: true

# 使用Hystrix Metrics Stream必备
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
  eureka:
    enabled: true

logging:
  level:
    com.silent.springcloud.service.PaymentService: debug

eureka:
  instance:
    instance-id: order80
    prefer-ip-address: true
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机版
      #defaultZone: http://localhost:7001/eureka
      # 集群版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka